import type { RecognitionPayload } from '@/models/level';

import marioPipeStairsStageUrl from './dummy-images/mario-pipe-stairs-stage.png';
import marioShortStageUrl from './dummy-images/mario-short-stage.png';
import marioVerticalStageUrl from './dummy-images/mario-vertical-stage.png';
import marioWideStageUrl from './dummy-images/mario-wide-stage.png';

export type RecognitionDebugSample = {
  id: string;
  label: string;
  payload: RecognitionPayload;
};

export const recognitionDebugSamples = [
  {
    id: 'preset-shapes',
    label: 'Preset shapes',
    payload: {
      id: 'preset-shapes-photo',
      name: 'Preset Shape Scan',
      image: {
        width: 1200,
        height: 800,
        name: 'preset-shapes.jpg',
      },
      objects: [
        {
          id: 'circle-a',
          shape: 'star',
          x: 120,
          y: 140,
          width: 160,
          height: 160,
          confidence: 0.92,
        },
        {
          id: 'triangle-a',
          shape: 'triangle',
          x: 340,
          y: 140,
          width: 180,
          height: 160,
          confidence: 0.9,
        },
        {
          id: 'line-a',
          shape: 'structure',
          x: 600,
          y: 180,
          width: 360,
          height: 48,
          confidence: 0.88,
        },
        {
          id: 'rectangle-a',
          shape: 'structure',
          x: 160,
          y: 480,
          width: 160,
          height: 220,
          confidence: 0.86,
        },
        {
          id: 'rectangle-b',
          shape: 'structure',
          x: 480,
          y: 500,
          width: 180,
          height: 140,
          confidence: 0.84,
        },
        {
          id: 'rectangle-c',
          shape: 'structure',
          x: 760,
          y: 460,
          width: 260,
          height: 200,
          confidence: 0.82,
        },
      ],
    },
  },
  {
    id: 'wide-room',
    label: 'Wide room',
    payload: {
      id: 'wide-room-photo',
      name: 'Wide Room Scan',
      image: {
        width: 1600,
        height: 900,
        name: 'wide-room.jpg',
      },
      objects: [
        {
          id: 'floor-01',
          shape: 'structure',
          x: 120,
          y: 640,
          width: 1360,
          height: 120,
          confidence: 0.96,
          data: {
            encoding: 'base64',
            mimeType: 'application/octet-stream',
            value: 'AAECAwQ=',
          },
        },
        {
          id: 'left-wall',
          shape: 'structure',
          x: 120,
          y: 120,
          width: 96,
          height: 640,
          confidence: 0.94,
        },
        {
          id: 'right-wall',
          shape: 'structure',
          x: 1384,
          y: 120,
          width: 96,
          height: 640,
          confidence: 0.93,
        },
        {
          id: 'door-01',
          shape: 'structure',
          x: 720,
          y: 520,
          width: 180,
          height: 240,
          confidence: 0.88,
        },
      ],
    },
  },
  {
    id: 'tall-room',
    label: 'Tall room',
    payload: {
      id: 'tall-room-photo',
      name: 'Tall Room Scan',
      image: {
        width: 900,
        height: 1600,
        name: 'tall-room.jpg',
      },
      objects: [
        {
          id: 'shaft-wall-left',
          shape: 'structure',
          x: 120,
          y: 160,
          width: 100,
          height: 1280,
          confidence: 0.91,
        },
        {
          id: 'shaft-wall-right',
          shape: 'structure',
          x: 680,
          y: 160,
          width: 100,
          height: 1280,
          confidence: 0.89,
        },
        {
          id: 'platform-top',
          shape: 'structure',
          x: 240,
          y: 280,
          width: 420,
          height: 80,
          confidence: 0.86,
        },
        {
          id: 'platform-bottom',
          shape: 'structure',
          x: 240,
          y: 1180,
          width: 420,
          height: 80,
          confidence: 0.87,
        },
      ],
    },
  },
  {
    id: 'overlap',
    label: 'Overlap',
    payload: {
      id: 'overlap-photo',
      name: 'Overlap Priority Scan',
      image: {
        width: 1200,
        height: 800,
        name: 'overlap.jpg',
      },
      objects: [
        {
          id: 'base-floor',
          shape: 'structure',
          x: 160,
          y: 520,
          width: 880,
          height: 120,
          confidence: 0.95,
        },
        {
          id: 'hazard-over-floor',
          shape: 'triangle',
          x: 500,
          y: 500,
          width: 240,
          height: 160,
          confidence: 0.83,
        },
        {
          id: 'spawn-over-hazard',
          shape: 'star',
          x: 580,
          y: 540,
          width: 120,
          height: 80,
          confidence: 0.79,
        },
      ],
    },
  },
  {
    id: 'mixed-shapes',
    label: 'Mixed shapes',
    payload: {
      id: 'mixed-shapes-photo',
      name: 'Mixed Shape Scan',
      image: {
        width: 1440,
        height: 1080,
        name: 'mixed-shapes.jpg',
      },
      objects: [
        {
          id: 'rectangle-window',
          shape: 'structure',
          x: 200,
          y: 180,
          width: 200,
          height: 180,
          confidence: 0.82,
        },
        {
          id: 'rectangle-crate',
          shape: 'structure',
          x: 480,
          y: 640,
          width: 180,
          height: 180,
          confidence: 0.9,
        },
        {
          id: 'circle-enemy',
          shape: 'star',
          x: 760,
          y: 600,
          width: 140,
          height: 220,
          confidence: 0.77,
        },
        {
          id: 'line-exit',
          shape: 'structure',
          x: 1080,
          y: 480,
          width: 160,
          height: 320,
          confidence: 0.85,
        },
      ],
    },
  },
  {
    id: 'mario-short-stage',
    label: 'Mario short stage',
    payload: {
      id: 'mario-short-stage-image',
      name: 'Mario Short Stage Line Art',
      image: {
        width: 640,
        height: 360,
        name: 'mario-short-stage.png',
        src: marioShortStageUrl,
      },
      objects: [
        {
          id: 'ground-line',
          shape: 'structure',
          x: 24,
          y: 310,
          width: 592,
          height: 12,
          confidence: 0.96,
        },
        {
          id: 'left-platform',
          shape: 'structure',
          x: 48,
          y: 270,
          width: 144,
          height: 34,
          confidence: 0.9,
        },
        {
          id: 'center-platform',
          shape: 'structure',
          x: 244,
          y: 238,
          width: 120,
          height: 30,
          confidence: 0.9,
        },
        {
          id: 'pipe',
          shape: 'structure',
          x: 506,
          y: 210,
          width: 62,
          height: 106,
          confidence: 0.92,
        },
        {
          id: 'enemy',
          shape: 'star',
          x: 370,
          y: 276,
          width: 36,
          height: 36,
          confidence: 0.84,
        },
        {
          id: 'hill',
          shape: 'triangle',
          x: 92,
          y: 210,
          width: 64,
          height: 50,
          confidence: 0.82,
        },
        {
          id: 'flag',
          shape: 'triangle',
          x: 578,
          y: 166,
          width: 48,
          height: 40,
          confidence: 0.8,
        },
      ],
    },
  },
  {
    id: 'mario-wide-stage',
    label: 'Mario wide stage',
    payload: {
      id: 'mario-wide-stage-image',
      name: 'Mario Wide Stage Line Art',
      image: {
        width: 960,
        height: 360,
        name: 'mario-wide-stage.png',
        src: marioWideStageUrl,
      },
      objects: [
        {
          id: 'left-ground-line',
          shape: 'structure',
          x: 24,
          y: 312,
          width: 270,
          height: 12,
          confidence: 0.96,
        },
        {
          id: 'right-ground-line',
          shape: 'structure',
          x: 374,
          y: 312,
          width: 562,
          height: 12,
          confidence: 0.96,
        },
        {
          id: 'left-blocks',
          shape: 'structure',
          x: 54,
          y: 220,
          width: 118,
          height: 38,
          confidence: 0.88,
        },
        {
          id: 'mid-platform',
          shape: 'structure',
          x: 342,
          y: 234,
          width: 170,
          height: 30,
          confidence: 0.9,
        },
        {
          id: 'right-platform',
          shape: 'structure',
          x: 612,
          y: 250,
          width: 134,
          height: 28,
          confidence: 0.9,
        },
        {
          id: 'pipe',
          shape: 'structure',
          x: 804,
          y: 188,
          width: 96,
          height: 130,
          confidence: 0.92,
        },
        {
          id: 'coins-a',
          shape: 'star',
          x: 292,
          y: 192,
          width: 60,
          height: 52,
          confidence: 0.78,
        },
        {
          id: 'coins-b',
          shape: 'star',
          x: 532,
          y: 208,
          width: 66,
          height: 28,
          confidence: 0.78,
        },
        {
          id: 'slope',
          shape: 'triangle',
          x: 708,
          y: 244,
          width: 144,
          height: 74,
          confidence: 0.82,
        },
      ],
    },
  },
  {
    id: 'mario-vertical-stage',
    label: 'Mario vertical stage',
    payload: {
      id: 'mario-vertical-stage-image',
      name: 'Mario Vertical Stage Line Art',
      image: {
        width: 480,
        height: 720,
        name: 'mario-vertical-stage.png',
        src: marioVerticalStageUrl,
      },
      objects: [
        {
          id: 'left-wall-line',
          shape: 'structure',
          x: 64,
          y: 60,
          width: 12,
          height: 614,
          confidence: 0.94,
        },
        {
          id: 'right-wall-line',
          shape: 'structure',
          x: 404,
          y: 60,
          width: 12,
          height: 614,
          confidence: 0.94,
        },
        {
          id: 'platforms-left',
          shape: 'structure',
          x: 112,
          y: 244,
          width: 178,
          height: 398,
          confidence: 0.9,
        },
        {
          id: 'platforms-right',
          shape: 'structure',
          x: 190,
          y: 152,
          width: 178,
          height: 398,
          confidence: 0.9,
        },
        {
          id: 'ladder',
          shape: 'structure',
          x: 236,
          y: 170,
          width: 32,
          height: 458,
          confidence: 0.82,
        },
        {
          id: 'coins',
          shape: 'star',
          x: 119,
          y: 303,
          width: 240,
          height: 302,
          confidence: 0.76,
        },
        {
          id: 'spike',
          shape: 'triangle',
          x: 236,
          y: 72,
          width: 48,
          height: 40,
          confidence: 0.76,
        },
      ],
    },
  },
  {
    id: 'mario-pipe-stairs-stage',
    label: 'Mario pipe stairs',
    payload: {
      id: 'mario-pipe-stairs-stage-image',
      name: 'Mario Pipe Stairs Line Art',
      image: {
        width: 640,
        height: 480,
        name: 'mario-pipe-stairs-stage.png',
        src: marioPipeStairsStageUrl,
      },
      objects: [
        {
          id: 'ground-line',
          shape: 'structure',
          x: 28,
          y: 426,
          width: 584,
          height: 12,
          confidence: 0.96,
        },
        {
          id: 'left-pipe',
          shape: 'structure',
          x: 58,
          y: 332,
          width: 80,
          height: 100,
          confidence: 0.92,
        },
        {
          id: 'right-pipe',
          shape: 'structure',
          x: 424,
          y: 288,
          width: 102,
          height: 144,
          confidence: 0.92,
        },
        {
          id: 'stairs',
          shape: 'structure',
          x: 190,
          y: 232,
          width: 200,
          height: 200,
          confidence: 0.88,
        },
        {
          id: 'floating-blocks',
          shape: 'structure',
          x: 334,
          y: 188,
          width: 90,
          height: 44,
          confidence: 0.86,
        },
        {
          id: 'enemies',
          shape: 'star',
          x: 136,
          y: 382,
          width: 420,
          height: 38,
          confidence: 0.78,
        },
        {
          id: 'hill',
          shape: 'triangle',
          x: 78,
          y: 260,
          width: 80,
          height: 66,
          confidence: 0.8,
        },
        {
          id: 'flag',
          shape: 'triangle',
          x: 548,
          y: 222,
          width: 58,
          height: 52,
          confidence: 0.8,
        },
      ],
    },
  },
] as const satisfies ReadonlyArray<RecognitionDebugSample>;
